# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/imkabir/c_programming/imlib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/imkabir/c_programming/imlib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/imkabir/c_programming/imlib/CMakeFiles /home/imkabir/c_programming/imlib//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/imkabir/c_programming/imlib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named imlib

# Build rule for target.
imlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imlib
.PHONY : imlib

# fast build rule for target.
imlib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/build
.PHONY : imlib/fast

#=============================================================================
# Target rules for targets named inheritance

# Build rule for target.
inheritance: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 inheritance
.PHONY : inheritance

# fast build rule for target.
inheritance/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/inheritance.dir/build.make CMakeFiles/inheritance.dir/build
.PHONY : inheritance/fast

#=============================================================================
# Target rules for targets named ll

# Build rule for target.
ll: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ll
.PHONY : ll

# fast build rule for target.
ll/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ll.dir/build.make CMakeFiles/ll.dir/build
.PHONY : ll/fast

examples/inheritance.o: examples/inheritance.c.o
.PHONY : examples/inheritance.o

# target to build an object file
examples/inheritance.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/inheritance.dir/build.make CMakeFiles/inheritance.dir/examples/inheritance.c.o
.PHONY : examples/inheritance.c.o

examples/inheritance.i: examples/inheritance.c.i
.PHONY : examples/inheritance.i

# target to preprocess a source file
examples/inheritance.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/inheritance.dir/build.make CMakeFiles/inheritance.dir/examples/inheritance.c.i
.PHONY : examples/inheritance.c.i

examples/inheritance.s: examples/inheritance.c.s
.PHONY : examples/inheritance.s

# target to generate assembly for a file
examples/inheritance.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/inheritance.dir/build.make CMakeFiles/inheritance.dir/examples/inheritance.c.s
.PHONY : examples/inheritance.c.s

examples/ll.o: examples/ll.c.o
.PHONY : examples/ll.o

# target to build an object file
examples/ll.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ll.dir/build.make CMakeFiles/ll.dir/examples/ll.c.o
.PHONY : examples/ll.c.o

examples/ll.i: examples/ll.c.i
.PHONY : examples/ll.i

# target to preprocess a source file
examples/ll.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ll.dir/build.make CMakeFiles/ll.dir/examples/ll.c.i
.PHONY : examples/ll.c.i

examples/ll.s: examples/ll.c.s
.PHONY : examples/ll.s

# target to generate assembly for a file
examples/ll.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ll.dir/build.make CMakeFiles/ll.dir/examples/ll.c.s
.PHONY : examples/ll.c.s

src/iiter.o: src/iiter.c.o
.PHONY : src/iiter.o

# target to build an object file
src/iiter.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/iiter.c.o
.PHONY : src/iiter.c.o

src/iiter.i: src/iiter.c.i
.PHONY : src/iiter.i

# target to preprocess a source file
src/iiter.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/iiter.c.i
.PHONY : src/iiter.c.i

src/iiter.s: src/iiter.c.s
.PHONY : src/iiter.s

# target to generate assembly for a file
src/iiter.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/iiter.c.s
.PHONY : src/iiter.c.s

src/ilist.o: src/ilist.c.o
.PHONY : src/ilist.o

# target to build an object file
src/ilist.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/ilist.c.o
.PHONY : src/ilist.c.o

src/ilist.i: src/ilist.c.i
.PHONY : src/ilist.i

# target to preprocess a source file
src/ilist.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/ilist.c.i
.PHONY : src/ilist.c.i

src/ilist.s: src/ilist.c.s
.PHONY : src/ilist.s

# target to generate assembly for a file
src/ilist.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/ilist.c.s
.PHONY : src/ilist.c.s

src/imbox.o: src/imbox.c.o
.PHONY : src/imbox.o

# target to build an object file
src/imbox.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imbox.c.o
.PHONY : src/imbox.c.o

src/imbox.i: src/imbox.c.i
.PHONY : src/imbox.i

# target to preprocess a source file
src/imbox.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imbox.c.i
.PHONY : src/imbox.c.i

src/imbox.s: src/imbox.c.s
.PHONY : src/imbox.s

# target to generate assembly for a file
src/imbox.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imbox.c.s
.PHONY : src/imbox.c.s

src/imclass.o: src/imclass.c.o
.PHONY : src/imclass.o

# target to build an object file
src/imclass.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imclass.c.o
.PHONY : src/imclass.c.o

src/imclass.i: src/imclass.c.i
.PHONY : src/imclass.i

# target to preprocess a source file
src/imclass.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imclass.c.i
.PHONY : src/imclass.c.i

src/imclass.s: src/imclass.c.s
.PHONY : src/imclass.s

# target to generate assembly for a file
src/imclass.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imclass.c.s
.PHONY : src/imclass.c.s

src/imerrno.o: src/imerrno.c.o
.PHONY : src/imerrno.o

# target to build an object file
src/imerrno.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imerrno.c.o
.PHONY : src/imerrno.c.o

src/imerrno.i: src/imerrno.c.i
.PHONY : src/imerrno.i

# target to preprocess a source file
src/imerrno.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imerrno.c.i
.PHONY : src/imerrno.c.i

src/imerrno.s: src/imerrno.c.s
.PHONY : src/imerrno.s

# target to generate assembly for a file
src/imerrno.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imerrno.c.s
.PHONY : src/imerrno.c.s

src/imerror.o: src/imerror.c.o
.PHONY : src/imerror.o

# target to build an object file
src/imerror.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imerror.c.o
.PHONY : src/imerror.c.o

src/imerror.i: src/imerror.c.i
.PHONY : src/imerror.i

# target to preprocess a source file
src/imerror.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imerror.c.i
.PHONY : src/imerror.c.i

src/imerror.s: src/imerror.c.s
.PHONY : src/imerror.s

# target to generate assembly for a file
src/imerror.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imerror.c.s
.PHONY : src/imerror.c.s

src/imio.o: src/imio.c.o
.PHONY : src/imio.o

# target to build an object file
src/imio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imio.c.o
.PHONY : src/imio.c.o

src/imio.i: src/imio.c.i
.PHONY : src/imio.i

# target to preprocess a source file
src/imio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imio.c.i
.PHONY : src/imio.c.i

src/imio.s: src/imio.c.s
.PHONY : src/imio.s

# target to generate assembly for a file
src/imio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imio.c.s
.PHONY : src/imio.c.s

src/imlog.o: src/imlog.c.o
.PHONY : src/imlog.o

# target to build an object file
src/imlog.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imlog.c.o
.PHONY : src/imlog.c.o

src/imlog.i: src/imlog.c.i
.PHONY : src/imlog.i

# target to preprocess a source file
src/imlog.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imlog.c.i
.PHONY : src/imlog.c.i

src/imlog.s: src/imlog.c.s
.PHONY : src/imlog.s

# target to generate assembly for a file
src/imlog.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imlog.c.s
.PHONY : src/imlog.c.s

src/immem.o: src/immem.c.o
.PHONY : src/immem.o

# target to build an object file
src/immem.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/immem.c.o
.PHONY : src/immem.c.o

src/immem.i: src/immem.c.i
.PHONY : src/immem.i

# target to preprocess a source file
src/immem.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/immem.c.i
.PHONY : src/immem.c.i

src/immem.s: src/immem.c.s
.PHONY : src/immem.s

# target to generate assembly for a file
src/immem.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/immem.c.s
.PHONY : src/immem.c.s

src/imoptres.o: src/imoptres.c.o
.PHONY : src/imoptres.o

# target to build an object file
src/imoptres.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imoptres.c.o
.PHONY : src/imoptres.c.o

src/imoptres.i: src/imoptres.c.i
.PHONY : src/imoptres.i

# target to preprocess a source file
src/imoptres.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imoptres.c.i
.PHONY : src/imoptres.c.i

src/imoptres.s: src/imoptres.c.s
.PHONY : src/imoptres.s

# target to generate assembly for a file
src/imoptres.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imoptres.c.s
.PHONY : src/imoptres.c.s

src/impanic.o: src/impanic.c.o
.PHONY : src/impanic.o

# target to build an object file
src/impanic.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/impanic.c.o
.PHONY : src/impanic.c.o

src/impanic.i: src/impanic.c.i
.PHONY : src/impanic.i

# target to preprocess a source file
src/impanic.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/impanic.c.i
.PHONY : src/impanic.c.i

src/impanic.s: src/impanic.c.s
.PHONY : src/impanic.s

# target to generate assembly for a file
src/impanic.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/impanic.c.s
.PHONY : src/impanic.c.s

src/imparam.o: src/imparam.c.o
.PHONY : src/imparam.o

# target to build an object file
src/imparam.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imparam.c.o
.PHONY : src/imparam.c.o

src/imparam.i: src/imparam.c.i
.PHONY : src/imparam.i

# target to preprocess a source file
src/imparam.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imparam.c.i
.PHONY : src/imparam.c.i

src/imparam.s: src/imparam.c.s
.PHONY : src/imparam.s

# target to generate assembly for a file
src/imparam.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imparam.c.s
.PHONY : src/imparam.c.s

src/imstr.o: src/imstr.c.o
.PHONY : src/imstr.o

# target to build an object file
src/imstr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imstr.c.o
.PHONY : src/imstr.c.o

src/imstr.i: src/imstr.c.i
.PHONY : src/imstr.i

# target to preprocess a source file
src/imstr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imstr.c.i
.PHONY : src/imstr.c.i

src/imstr.s: src/imstr.c.s
.PHONY : src/imstr.s

# target to generate assembly for a file
src/imstr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imstr.c.s
.PHONY : src/imstr.c.s

src/imwrap.o: src/imwrap.c.o
.PHONY : src/imwrap.o

# target to build an object file
src/imwrap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imwrap.c.o
.PHONY : src/imwrap.c.o

src/imwrap.i: src/imwrap.c.i
.PHONY : src/imwrap.i

# target to preprocess a source file
src/imwrap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imwrap.c.i
.PHONY : src/imwrap.c.i

src/imwrap.s: src/imwrap.c.s
.PHONY : src/imwrap.s

# target to generate assembly for a file
src/imwrap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/imwrap.c.s
.PHONY : src/imwrap.c.s

src/linkedlist.o: src/linkedlist.c.o
.PHONY : src/linkedlist.o

# target to build an object file
src/linkedlist.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/linkedlist.c.o
.PHONY : src/linkedlist.c.o

src/linkedlist.i: src/linkedlist.c.i
.PHONY : src/linkedlist.i

# target to preprocess a source file
src/linkedlist.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/linkedlist.c.i
.PHONY : src/linkedlist.c.i

src/linkedlist.s: src/linkedlist.c.s
.PHONY : src/linkedlist.s

# target to generate assembly for a file
src/linkedlist.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imlib.dir/build.make CMakeFiles/imlib.dir/src/linkedlist.c.s
.PHONY : src/linkedlist.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... imlib"
	@echo "... inheritance"
	@echo "... ll"
	@echo "... examples/inheritance.o"
	@echo "... examples/inheritance.i"
	@echo "... examples/inheritance.s"
	@echo "... examples/ll.o"
	@echo "... examples/ll.i"
	@echo "... examples/ll.s"
	@echo "... src/iiter.o"
	@echo "... src/iiter.i"
	@echo "... src/iiter.s"
	@echo "... src/ilist.o"
	@echo "... src/ilist.i"
	@echo "... src/ilist.s"
	@echo "... src/imbox.o"
	@echo "... src/imbox.i"
	@echo "... src/imbox.s"
	@echo "... src/imclass.o"
	@echo "... src/imclass.i"
	@echo "... src/imclass.s"
	@echo "... src/imerrno.o"
	@echo "... src/imerrno.i"
	@echo "... src/imerrno.s"
	@echo "... src/imerror.o"
	@echo "... src/imerror.i"
	@echo "... src/imerror.s"
	@echo "... src/imio.o"
	@echo "... src/imio.i"
	@echo "... src/imio.s"
	@echo "... src/imlog.o"
	@echo "... src/imlog.i"
	@echo "... src/imlog.s"
	@echo "... src/immem.o"
	@echo "... src/immem.i"
	@echo "... src/immem.s"
	@echo "... src/imoptres.o"
	@echo "... src/imoptres.i"
	@echo "... src/imoptres.s"
	@echo "... src/impanic.o"
	@echo "... src/impanic.i"
	@echo "... src/impanic.s"
	@echo "... src/imparam.o"
	@echo "... src/imparam.i"
	@echo "... src/imparam.s"
	@echo "... src/imstr.o"
	@echo "... src/imstr.i"
	@echo "... src/imstr.s"
	@echo "... src/imwrap.o"
	@echo "... src/imwrap.i"
	@echo "... src/imwrap.s"
	@echo "... src/linkedlist.o"
	@echo "... src/linkedlist.i"
	@echo "... src/linkedlist.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

